/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CODIGOS;

import java.awt.event.ActionEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author irmoura
 */
public class Tela extends javax.swing.JFrame {
    
    Cronometro contagem;
    public Timer timer2;
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        COMBO_HORAS = new javax.swing.JComboBox<>();
        LABEL_HORA_ATUAL = new javax.swing.JLabel();
        COMBO_MINUTOS = new javax.swing.JComboBox<>();
        BTN_INICIAR = new javax.swing.JButton();
        BTN_PARAR = new javax.swing.JButton();
        LABEL_TESTE = new javax.swing.JLabel();
        LABEL_TEMPO_DECORRIDO = new javax.swing.JLabel();
        LABEL_TEMPO_RESTANTE = new javax.swing.JLabel();
        LABEL_PORCENT_PROGRESSIVA = new javax.swing.JLabel();
        LABEL_PORCENT_REGRESSIVA = new javax.swing.JLabel();
        BARRA_PROGRESSIVA = new javax.swing.JProgressBar();
        BARRA_REGRESSIVA = new javax.swing.JProgressBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clock");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        COMBO_HORAS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        COMBO_HORAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        LABEL_HORA_ATUAL.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_HORA_ATUAL.setText("--:--:--");

        COMBO_MINUTOS.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        COMBO_MINUTOS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        BTN_INICIAR.setText("Iniciar");
        BTN_INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_INICIARActionPerformed(evt);
            }
        });

        BTN_PARAR.setText("Parar");
        BTN_PARAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PARARActionPerformed(evt);
            }
        });

        LABEL_TESTE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_TESTE.setText("--:--:--");

        LABEL_TEMPO_DECORRIDO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_TEMPO_DECORRIDO.setText("--:--:--");

        LABEL_TEMPO_RESTANTE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_TEMPO_RESTANTE.setText("--:--:--");

        LABEL_PORCENT_PROGRESSIVA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_PORCENT_PROGRESSIVA.setText("--:--:--");

        LABEL_PORCENT_REGRESSIVA.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LABEL_PORCENT_REGRESSIVA.setText("--:--:--");

        jDesktopPane1.setLayer(COMBO_HORAS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LABEL_HORA_ATUAL, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(COMBO_MINUTOS, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BTN_INICIAR, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BTN_PARAR, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LABEL_TESTE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LABEL_TEMPO_DECORRIDO, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LABEL_TEMPO_RESTANTE, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LABEL_PORCENT_PROGRESSIVA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(LABEL_PORCENT_REGRESSIVA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BARRA_PROGRESSIVA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(BARRA_REGRESSIVA, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(COMBO_HORAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(COMBO_MINUTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(BTN_INICIAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_PARAR))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LABEL_TEMPO_RESTANTE)
                            .addComponent(LABEL_TESTE)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LABEL_TEMPO_DECORRIDO)
                                    .addComponent(LABEL_HORA_ATUAL))
                                .addGap(234, 234, 234)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LABEL_PORCENT_PROGRESSIVA)
                                    .addComponent(LABEL_PORCENT_REGRESSIVA))
                                .addGap(196, 196, 196)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BARRA_REGRESSIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BARRA_PROGRESSIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(134, 228, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(LABEL_HORA_ATUAL)
                        .addGap(18, 18, 18)
                        .addComponent(LABEL_TEMPO_DECORRIDO))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABEL_PORCENT_PROGRESSIVA)
                            .addComponent(BARRA_PROGRESSIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LABEL_PORCENT_REGRESSIVA)
                            .addComponent(BARRA_REGRESSIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL_TEMPO_RESTANTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL_TESTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COMBO_HORAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COMBO_MINUTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_INICIAR)
                    .addComponent(BTN_PARAR))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        new Thread_HoraAtual().Run();
        
        BTN_PARAR.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void BTN_INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_INICIARActionPerformed
        // TODO add your handling code here:
        if(!((COMBO_HORAS.getSelectedIndex() == 0) && (COMBO_MINUTOS.getSelectedIndex() == 0))){
            /*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/
            BTN_INICIAR.setEnabled(false);
            COMBO_HORAS.setEnabled(false);
            COMBO_MINUTOS.setEnabled(false);
            /*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/
            BTN_PARAR.setEnabled(true);
            /*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/
            contagem = new Cronometro(0, 0, 0, Integer.parseInt(""+COMBO_HORAS.getSelectedItem()), Integer.parseInt(""+COMBO_MINUTOS.getSelectedItem()), 0, Cronometro.REGRESSIVA);
            contagem.cronometro();
            /*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/
            Teste.marca_tempo(""+COMBO_HORAS.getSelectedItem()+":"+COMBO_MINUTOS.getSelectedItem()+":00");  
            LABEL_TESTE.setText("INICIO - "+Teste.horario_do_inicio+" | "+"FIM - "+Teste.horario_do_fim);
            String fim = Teste.horario_do_fim;
            /*----------------------------------------------------------------*/
            /*ZERA AS VARIAVEIS QUE MOSTRAM INICIO E FIM DOS HORARIOS*/
            Teste.horario_do_inicio = "";
    
            Teste.ss = 0; 
            Teste.segundos_totais = 0;
            Teste.mm = 0;
            Teste.hh = 0;

            Teste.ss_2 = 0;
            Teste.mm_2 = 0;
            Teste.hh_2 = 0;

            Teste.segundos = "";
            Teste.minutos = "";
            Teste.horas = "";
            Teste.cronometro_string = "";
            Teste.horario_do_fim = "";

            Teste.segundos_finais = "";
            Teste.minutos_finais = "";
            Teste.horas_finais = "";
            /*----------------------------------------------------------------*/
            timer2 = new Timer(1000, (ActionEvent e) -> {
                LABEL_TEMPO_RESTANTE.setText("Tempo Restante | "+contagem.getTime());   
                Metodos.tempo_decorrido(""+COMBO_HORAS.getSelectedItem(), ""+COMBO_MINUTOS.getSelectedItem());
                LABEL_TEMPO_DECORRIDO.setText("Tempo Decorrido | "+Metodos.cronometro_string);
                DecimalFormat deci = new DecimalFormat("0.00");
                LABEL_PORCENT_PROGRESSIVA.setText(deci.format(Metodos.porcentagem)+"%");//""+Metodos.porcentagem
                LABEL_PORCENT_REGRESSIVA.setText(deci.format(Metodos.porcentagem_regressiva)+"%");//""+Metodos.porcentagem
                /*------------------------------------------------------------*/
                /*PROCESSA OS VALORES PARA A BARRA PROGRESSIVA*/
                DecimalFormat deci2 = new DecimalFormat("0");
                String vp = ""+deci2.format(Metodos.porcentagem);
                int vpi = Integer.parseInt(""+vp);
                BARRA_PROGRESSIVA.setValue(vpi);
                /*------------------------------------------------------------*/
                /*------------------------------------------------------------*/
                /*PROCESSA OS VALORES PARA A BARRA PROGRESSIVA*/
                DecimalFormat deci3 = new DecimalFormat("0");
                String vp2 = ""+deci3.format(Metodos.porcentagem_regressiva);
                int vpi2 = Integer.parseInt(""+vp2);
                BARRA_REGRESSIVA.setValue(vpi2);
                /*------------------------------------------------------------*/
                if(LABEL_HORA_ATUAL.getText().equals("Hora Atual | "+fim)){      
                    Metodos.contador_porcentagem = 0;//ZERA A PORCENTAGEM
                    BTN_PARARActionPerformed(null);
                    BTN_PARAR.setEnabled(false); 
                    JOptionPane.showMessageDialog(null,"Fim do tempo");
                }
            });
        
        timer2.start();
        }
    }//GEN-LAST:event_BTN_INICIARActionPerformed

    private void BTN_PARARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PARARActionPerformed
        // TODO add your handling code here:
        timer2.stop();    
        /*ZERA AS INFORMACOES*/
        Metodos.zerador();
    }//GEN-LAST:event_BTN_PARARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Tela().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar BARRA_PROGRESSIVA;
    public static javax.swing.JProgressBar BARRA_REGRESSIVA;
    public static javax.swing.JButton BTN_INICIAR;
    public static javax.swing.JButton BTN_PARAR;
    public static javax.swing.JComboBox<String> COMBO_HORAS;
    public static javax.swing.JComboBox<String> COMBO_MINUTOS;
    public static javax.swing.JLabel LABEL_HORA_ATUAL;
    public static javax.swing.JLabel LABEL_PORCENT_PROGRESSIVA;
    public static javax.swing.JLabel LABEL_PORCENT_REGRESSIVA;
    public static javax.swing.JLabel LABEL_TEMPO_DECORRIDO;
    public static javax.swing.JLabel LABEL_TEMPO_RESTANTE;
    public static javax.swing.JLabel LABEL_TESTE;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    public class Thread_HoraAtual extends Thread{
        public void Run(){
            Timer timer = new Timer(0, (ActionEvent e) -> {
                SimpleDateFormat hora_completa = new SimpleDateFormat("hh:mm:ss");
                LABEL_HORA_ATUAL.setText("Hora Atual | "+hora_completa.format(new Date()));
            });

            timer.start();
        }
    }
}
